
version: '2.1'
services:
  web:
    image: nginx
    container_name: nginx3
    restart: always
    volumes:
     - ./www:/www
     - ./site.conf:/etc/nginx/conf.d/site.conf
    ports:
     - "80:80"
    links:
     - php

  php:
    build: .
    container_name: php-fpm3
    volumes:
     - ./www:/www
    links:
     - db

  db:
    image: mysql:8.0
    container_name: mysql3
    restart: always
    ports:
     - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: teste
